### ISSUE TITLE
couple ideas

### ISSUE THREAD

**Issue by Fletcher208** [Benjamin-Casey/Bens-Brilliant-World#2]

**Comment by Benjamin-Casey** [comment]
luigionpot — Today at 9:23 PM
Event: Spawn Warden next to every player
Event: Remove all players hunger
Event: Encase all players in Obsidian
Event: Remove a random item from every players inventory
Event: Give all players blindness for a timed amount. Different amounts for different players. (one dude gets it for 5 mins)
Event: All tools change to golden variants
Event: Set all players health to 1 heart
Event: Teleport all players 2000 blocks in a random direction
Event: all players get mining fatigue
Event: All torches get deleted.
Event: All mobs get increased health and speed
Event: Give all players the poison effect for 20 seconds
luigionpot — Today at 9:30 PM
Event: Spawn four creepers near every player (10 blocks away, one in each direction roughly)
Event: Make the sun burn players
Event: Spawn Lava in a random spot near the player
Event: Teleport every player into the Nether
Event: All players armour breaks
Event: All Zombies become Husks, All skeletons become Strays
Event: Wither spawns next to every player
Event: All players get Nausea
